FROM python:3.12-slim
WORKDIR /app
COPY ./backend /app/backend/
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Port for flask backend
EXPOSE 5000

CMD ["python", "./backend/run.py"]