version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
