name: Test the project
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [3.12.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Fetch code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Test
        run: python -m pytest
        shell: bash
